// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWPFcw0qjy1DjYEgJLqUSJ774XRQ9GsaM',
    appId: '1:58719256711:web:38d5dd86f2164579a3b822',
    messagingSenderId: '58719256711',
    projectId: 'unienrollnew',
    authDomain: 'unienrollnew.firebaseapp.com',
    storageBucket: 'unienrollnew.firebasestorage.app',
    measurementId: 'G-T92R37E1TK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0aozQolIKtz106PqbFH1m0zNZuYHdPgQ',
    appId: '1:58719256711:android:a2c0b9e5ae492785a3b822',
    messagingSenderId: '58719256711',
    projectId: 'unienrollnew',
    storageBucket: 'unienrollnew.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBIMmMJ9nuwtI5cr1BY_rBV-urrHYdyWLM',
    appId: '1:58719256711:ios:51dd416915786fe0a3b822',
    messagingSenderId: '58719256711',
    projectId: 'unienrollnew',
    storageBucket: 'unienrollnew.firebasestorage.app',
    iosBundleId: 'com.example.unienrollStudent',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBIMmMJ9nuwtI5cr1BY_rBV-urrHYdyWLM',
    appId: '1:58719256711:ios:51dd416915786fe0a3b822',
    messagingSenderId: '58719256711',
    projectId: 'unienrollnew',
    storageBucket: 'unienrollnew.firebasestorage.app',
    iosBundleId: 'com.example.unienrollStudent',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDWPFcw0qjy1DjYEgJLqUSJ774XRQ9GsaM',
    appId: '1:58719256711:web:f1e45ef7f1fffcc5a3b822',
    messagingSenderId: '58719256711',
    projectId: 'unienrollnew',
    authDomain: 'unienrollnew.firebaseapp.com',
    storageBucket: 'unienrollnew.firebasestorage.app',
    measurementId: 'G-0113LD42JF',
  );
}
